#!/usr/bin/env python3
"""
webGenerator.py
Author: MyrrhJessica Okwara <okwaram2@lasalle.edu>
Boilerplate generated by: Paul Tran <tranb9@lasalle.edu>

Generates a simple static website from the Philadelphia history data.

This scripts takes synthesized data from data/entries/<topic>.txt and loads
the data into a webpage (based on the predefined template in web/template.html).
Output webpages are written to data/web/<topic>.html.
"""

from pathlib import Path

def loadTemplate() -> str:
    """Returns the template HTML for a webpage."""
    with open("web/template.html", "r") as file:
        script = file.read()
    print(script)
    return script

def clearTemplate() -> str:
    """Clears all placeholder texts and images from the template."""
    script = loadTemplate()
    # Additional code goes here, make sure you have only the HTML boilerplate.
    
    return script

def insertDataIntoTemplate(template: str, data: dict[str, str]) -> str:
    """Inserts the synthesized data into the template."""
    script = ""
    

    return script
    
if __name__ == "__main__":
    loadTemplate()