#!/usr/bin/env python3
"""
webGenerator.py
Author: MyrrhJessica Okwara <okwaram2@lasalle.edu>
Boilerplate generated by: Paul Tran <tranb9@lasalle.edu>

Generates a simple static website from the Philadelphia history data.

This scripts takes synthesized data from data/entries/<topic>.txt and loads
the data into a webpage (based on the predefined template in web/template.html).
Output webpages are written to data/web/<topic>.html.
"""

import os
import re
from pathlib import Path

rootDir = Path(__file__).parent.parent.parent

def loadTemplate() -> str:
    """Returns the template HTML for a webpage."""
    with open(rootDir / "web" / "template.html", "r", encoding="utf-8") as file:
        script = file.read()
    print("Loaded template from web/template.html")
    return script

def clearTemplate() -> str:
    """Clears all placeholder texts and images from the template."""
    script = loadTemplate()
    return script

def loadCategory(topic: str) -> str:
    """
    Looks up the category of a topic from data/topics.txt.
    Returns the category string, or 'general' if not found.
    """
    try:
        with open(rootDir / "data" / "topics.txt", "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if "; " in line:
                    name, category = line.rsplit("; ", 1)
                    if name.strip().lower() == topic.strip().lower():
                        return category.strip()
    except Exception:
        pass
    return "Philadelphia History"

def parse_entry_file(filepath: Path) -> dict:
    """
    Parses a synthesized entry file from data/entries/<topic>.txt.
    Extracts the title, Infobox elements, and subsequent sections.
    """
    content = filepath.read_text(encoding="utf-8")
    lines = content.splitlines()
    
    title = filepath.stem
    infobox = []
    sections = {}
    sections_ordered = []
    
    current_section = None
    section_lines = []
    
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            title = stripped[3:].strip()
        elif stripped.startswith("### "):
            # Save previous section
            if current_section:
                sections[current_section] = "\n".join(section_lines).strip()
            current_section = stripped[4:].strip()
            if current_section not in sections_ordered:
                sections_ordered.append(current_section)
            section_lines = []
        else:
            if current_section:
                section_lines.append(line)
            elif not title and stripped:
                title = stripped
                
    if current_section:
        sections[current_section] = "\n".join(section_lines).strip()
        
    # Parse Infobox specifically
    if "Infobox" in sections:
        infobox_content = sections["Infobox"]
        for l in infobox_content.splitlines():
            l_strip = l.strip()
            if l_strip.startswith("|") and l_strip.endswith("|"):
                parts = [p.strip() for p in l_strip.split("|")[1:-1]]
                if len(parts) >= 2:
                    key = parts[0].replace("**", "").strip()
                    val = parts[1].strip()
                    if key and val and not all(c == '-' for c in key) and key.lower() != "known for":
                        infobox.append((key, val))
                        
    return {
        "title": title,
        "infobox": infobox,
        "sections": sections,
        "sections_ordered": sections_ordered
    }

def markdown_to_html(md_text: str) -> str:
    """Converts a simple markdown text block to styled HTML."""
    html_lines = []
    in_list = False
    in_ordered_list = False
    
    for line in md_text.splitlines():
        stripped = line.strip()
        if not stripped:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            if in_ordered_list:
                html_lines.append("</ol>")
                in_ordered_list = False
            continue
            
        # Inline styling (Bold and Links)
        processed = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', line)
        processed = re.sub(r'\[(.*?)\]\((.*?)\)', r'<a href="\2" class="text-blue-600 hover:underline" target="_blank">\1</a>', processed)
        
        # Bullet Lists
        if stripped.startswith("* ") or stripped.startswith("- "):
            if not in_list:
                if in_ordered_list:
                    html_lines.append("</ol>")
                    in_ordered_list = False
                html_lines.append('<ul class="list-disc list-inside space-y-1 mb-4 text-slate-600">')
                in_list = True
            item_text = processed.strip()[2:].strip()
            html_lines.append(f'<li>{item_text}</li>')
        # Numbered Lists
        elif re.match(r'^\d+\.\s', stripped):
            if not in_ordered_list:
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append('<ol class="list-decimal list-inside space-y-1 mb-4 text-slate-600">')
                in_ordered_list = True
            item_text = re.sub(r'^\d+\.\s+', '', processed.strip()).strip()
            html_lines.append(f'<li>{item_text}</li>')
        else:
            # Paragraph
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            if in_ordered_list:
                html_lines.append("</ol>")
                in_ordered_list = False
            html_lines.append(f'<p class="mb-4 text-slate-600 leading-relaxed">{processed.strip()}</p>')
            
    if in_list:
        html_lines.append("</ul>")
    if in_ordered_list:
        html_lines.append("</ol>")
        
    return "\n".join(html_lines)

def insertDataIntoTemplate(template: str, data: dict) -> str:
    """Inserts the synthesized data into the template."""
    script = template
    
    # 1. Simple replacements
    script = script.replace("<title>Project250 - [##########]</title>", f"<title>Project250 - {data['title']}</title>")
    script = script.replace("<h1 class=\"text-5xl font-bold leading-tight uppercase\">[##########]</h1>", f"<h1 class=\"text-5xl font-bold leading-tight uppercase\">{data['title']}</h1>")
    script = script.replace("<p class=\"text-lg text-slate-300 max-w-lg\">[##########]</p>", f"<p class=\"text-lg text-slate-300 max-w-lg\">{data['lead']}</p>")
    script = script.replace("<h3 class=\"text-3xl font-bold\">[##########]</h3>", f"<h3 class=\"text-3xl font-bold\">{data['title']}</h3>")
    
    # 2. Generate Left Navigation
    sidebar_items_html = ""
    first = True
    for sec_title in data['sections_ordered']:
        if sec_title.lower() in ("infobox", "lead section"):
            continue
        sec_id = sec_title.lower().replace(" ", "-")
        if first:
            sidebar_items_html += f'                    <li class="bg-slate-200 text-slate-900 p-2 rounded cursor-pointer font-medium"><a href="#{sec_id}" class="block w-full">{sec_title}</a></li>\n'
            first = False
        else:
            sidebar_items_html += f'                    <li class="hover:bg-slate-100 p-2 rounded cursor-pointer transition"><a href="#{sec_id}" class="block w-full">{sec_title}</a></li>\n'
            
    sidebar_block_old = '''                <ul class="space-y-1 text-sm text-slate-500">
                    <li class="bg-slate-200 text-slate-900 p-2 rounded cursor-pointer font-medium">[##########]
                    </li>
                    <li class="hover:bg-slate-100 p-2 rounded cursor-pointer transition">[##########]</li>
                    <li class="hover:bg-slate-100 p-2 rounded cursor-pointer transition">[##########]</li>
                    <li class="hover:bg-slate-100 p-2 rounded cursor-pointer transition">[##########]</li>
                    <li class="hover:bg-slate-100 p-2 rounded cursor-pointer transition">[##########]</li>
                </ul>'''
    sidebar_block_new = f'''                <ul class="space-y-1 text-sm text-slate-500">
{sidebar_items_html}                </ul>'''
    script = script.replace(sidebar_block_old, sidebar_block_new)
            
    # 3. Generate Main Content
    article_html = ""
    for sec_title in data['sections_ordered']:
        if sec_title.lower() in ("infobox", "lead section"):
            continue
        sec_id = sec_title.lower().replace(" ", "-")
        sec_content_html = data['sections_html'].get(sec_title, "")
        article_html += f'''
        <div class="mb-12 border-b pb-8 scroll-mt-20" id="{sec_id}">
            <h3 class="text-2xl font-bold text-slate-800 mb-4">{sec_title}</h3>
            <div class="text-slate-600 leading-relaxed space-y-4">
                {sec_content_html}
            </div>
        </div>
        '''
        
    body_start = script.find('<div class="prose prose-slate max-w-none text-slate-600 leading-relaxed">')
    if body_start != -1:
        body_end = script.find('</div>', body_start)
        if body_end != -1:
            target_body = script[body_start:body_end+6]
            replacement_body = f'<div class="space-y-8">{article_html}</div>'
            script = script.replace(target_body, replacement_body)

    # 4. Generate Right Infobox Sidebar
    infobox_html = ""
    if data['infobox']:
        for key, val in data['infobox']:
            infobox_html += f'''            <div class="flex flex-col border-b pb-2 last:border-0 last:pb-0">
                <span class="text-xs text-slate-400 uppercase tracking-wider font-semibold">{key}</span>
                <span class="text-sm text-slate-800 mt-0.5">{val}</span>
            </div>\n'''
    else:
        infobox_html = f'''            <div class="flex flex-col border-b pb-2">
                <span class="text-xs text-slate-400 uppercase tracking-wider font-semibold">Category</span>
                <span class="text-sm text-slate-800 mt-0.5">{data.get("category", "General").title()}</span>
            </div>
            <div class="flex flex-col border-b pb-2">
                <span class="text-xs text-slate-400 uppercase tracking-wider font-semibold">Location</span>
                <span class="text-sm text-slate-800 mt-0.5">Philadelphia, PA</span>
            </div>
            <div class="flex flex-col">
                <span class="text-xs text-slate-400 uppercase tracking-wider font-semibold">Era</span>
                <span class="text-sm text-slate-800 mt-0.5">1776 - 2026</span>
            </div>\n'''

    info_block_old = '''                    <div class="space-y-3 text-sm">
                        <div class="flex flex-col"><span class="text-slate-400 font-medium">[##########]</span><span
                                class="text-slate-800">[##########]</span></div>
                        <div class="flex flex-col"><span class="text-slate-400 font-medium">[##########]</span><span
                                class="text-slate-800">[##########]</span></div>
                        <div class="flex flex-col"><span class="text-slate-400 font-medium">[##########]</span><span
                                class="text-slate-800">[##########]</span></div>
                        <div class="flex flex-col"><span class="text-slate-400 font-medium">[##########]</span><span
                                class="text-slate-800">[##########]</span></div>
                    </div>'''
    info_block_new = f'''                    <div class="space-y-4 text-sm">
{infobox_html}                    </div>'''
    script = script.replace(info_block_old, info_block_new)
            
    # 5. Interactive Section Tags
    tags_old = '''                            <span
                                class="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded-full font-bold">[##########]</span>
                            <span
                                class="text-xs bg-slate-100 text-slate-600 px-2 py-1 rounded-full font-bold">[##########]</span>'''
    tags_new = f'''                            <span
                                class="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded-full font-bold">{data.get("category", "General").upper()}</span>
                            <span
                                class="text-xs bg-slate-100 text-slate-600 px-2 py-1 rounded-full font-bold">PHILADELPHIA</span>'''
    script = script.replace(tags_old, tags_new)
                            
    # 6. Semiquincentennial Hub Cards
    other_topics = data.get("other_topics", [])
    other_topics_categories = data.get("other_topics_categories", {})
    
    default_cards = [
        ("Independence Hall", "Landmark"),
        ("Liberty Bell", "Landmark"),
        ("Constitutional Convention", "Event")
    ]
    
    cards_to_show = []
    for idx in range(3):
        if idx < len(other_topics):
            topic_name_card = other_topics[idx]
            topic_cat_card = other_topics_categories.get(topic_name_card, "Philadelphia History")
            cards_to_show.append((topic_name_card, topic_cat_card, True))
        else:
            fallback_item = default_cards[idx]
            if fallback_item[0].lower() == data["title"].lower():
                fallback_item = ("Philadelphia Museum of Art", "Landmark")
            cards_to_show.append((fallback_item[0], fallback_item[1], False))
            
    # Replace Card 1
    name1, cat1, is_link1 = cards_to_show[0]
    href1 = f"./{name1}.html" if is_link1 else "#"
    card1_old = '''                <!-- Grid Card 1 -->
                <div class="bg-white rounded-xl shadow-sm border overflow-hidden group cursor-pointer">
                    <div class="h-40 overflow-hidden">
                        <img src="./istockphoto-1437085733-612x612.jpg"
                            class="w-full h-full object-cover group-hover:scale-105 transition duration-500">
                    </div>
                    <div class="p-4">
                        <h4 class="font-bold text-sm">[##########]</h4>
                        <p class="text-xs text-slate-500 mt-1">[##########]</p>
                    </div>
                </div>'''
    card1_new = f'''                <!-- Grid Card 1 -->
                <a href="{href1}" class="bg-white rounded-xl shadow-sm border overflow-hidden group cursor-pointer block">
                    <div class="h-40 overflow-hidden">
                        <img src="./istockphoto-1437085733-612x612.jpg"
                            class="w-full h-full object-cover group-hover:scale-105 transition duration-500">
                    </div>
                    <div class="p-4">
                        <h4 class="font-bold text-sm">{name1}</h4>
                        <p class="text-xs text-slate-500 mt-1">{cat1}</p>
                    </div>
                </a>'''
    script = script.replace(card1_old, card1_new)

    # Replace Card 2
    name2, cat2, is_link2 = cards_to_show[2] if len(cards_to_show) > 2 else cards_to_show[1]
    href2 = f"./{name2}.html" if is_link2 else "#"
    card2_old = '''                <!-- Grid Card 2 -->
                <div class="bg-white rounded-xl shadow-sm border overflow-hidden group cursor-pointer">
                    <div class="h-40 overflow-hidden">
                        <img src="https://cdn.britannica.com/95/170195-050-EFCB2F83/ENIAC-1946.jpg"
                            class="w-full h-full object-cover group-hover:scale-105 transition duration-500">
                    </div>
                    <div class="p-4">
                        <h4 class="font-bold text-sm">[##########]</h4>
                        <p class="text-xs text-slate-500 mt-1">[##########]</p>
                    </div>
                </div>'''
    card2_new = f'''                <!-- Grid Card 2 -->
                <a href="{href2}" class="bg-white rounded-xl shadow-sm border overflow-hidden group cursor-pointer block">
                    <div class="h-40 overflow-hidden">
                        <img src="https://cdn.britannica.com/95/170195-050-EFCB2F83/ENIAC-1946.jpg"
                            class="w-full h-full object-cover group-hover:scale-105 transition duration-500">
                    </div>
                    <div class="p-4">
                        <h4 class="font-bold text-sm">{name2}</h4>
                        <p class="text-xs text-slate-500 mt-1">{cat2}</p>
                    </div>
                </a>'''
    script = script.replace(card2_old, card2_new)

    # Replace Card 3
    name3, cat3, is_link3 = cards_to_show[1] if len(cards_to_show) > 2 else cards_to_show[1] # swap indices to be diverse
    if len(cards_to_show) > 2:
        name3, cat3, is_link3 = cards_to_show[2]
    href3 = f"./{name3}.html" if is_link3 else "#"
    card3_old = '''                <!-- Grid Card 3 -->
                <div class="bg-white rounded-xl shadow-sm border overflow-hidden group cursor-pointer">
                    <div class="h-40 overflow-hidden">
                        <img src="https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=400"
                            class="w-full h-full object-cover group-hover:scale-105 transition duration-500">
                    </div>
                    <div class="p-4">
                        <h4 class="font-bold text-sm">[##########]</h4>
                        <p class="text-xs text-slate-500 mt-1">[##########]</p>
                    </div>
                </div>'''
    card3_new = f'''                <!-- Grid Card 3 -->
                <a href="{href3}" class="bg-white rounded-xl shadow-sm border overflow-hidden group cursor-pointer block">
                    <div class="h-40 overflow-hidden">
                        <img src="https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=400"
                            class="w-full h-full object-cover group-hover:scale-105 transition duration-500">
                    </div>
                    <div class="p-4">
                        <h4 class="font-bold text-sm">{name3}</h4>
                        <p class="text-xs text-slate-500 mt-1">{cat3}</p>
                    </div>
                </a>'''
    script = script.replace(card3_old, card3_new)
    
    # 7. Final sanitisation
    script = script.replace("[##########]", "")
        
    return script

def main() -> None:
    # 1. Scan for entries
    entries_dir = rootDir / "data" / "entries"
    if not entries_dir.exists():
        print(f"Error: {entries_dir} does not exist.")
        return
        
    entry_files = list(entries_dir.glob("*.txt"))
    topics = [f.stem for f in entry_files]
    
    if not topics:
        print("No synthesized entry files found in data/entries/")
        return
        
    print(f"Found {len(topics)} topics: {', '.join(topics)}")
    
    # 2. Get category mapping for all topics
    topics_categories = {t: loadCategory(t) for t in topics}
    
    # 3. Load basic HTML template
    template_html = clearTemplate()
    
    # 4. Create data/web folder if not exists
    web_dir = rootDir / "data" / "web"
    web_dir.mkdir(parents=True, exist_ok=True)
    
    # 5. Process each entry
    for filepath in entry_files:
        topic_name = filepath.stem
        print(f"Generating website for: {topic_name}...")
        
        parsed = parse_entry_file(filepath)
        category = topics_categories.get(topic_name, "Philadelphia History")
        parsed["category"] = category
        
        # Determine lead section
        lead_content = parsed["sections"].get("Lead section", "")
        parsed["lead"] = lead_content.strip()
        
        # Convert all sections to HTML
        sections_html = {}
        for sec_name, sec_md in parsed["sections"].items():
            sections_html[sec_name] = markdown_to_html(sec_md)
        parsed["sections_html"] = sections_html
        
        # Load Works Cited from data/search/{topic}.txt
        search_file = rootDir / "data" / "search" / f"{topic_name}.txt"
        works_cited_urls = []
        if search_file.exists():
            with open(search_file, "r", encoding="utf-8") as sf:
                works_cited_urls = [line.strip() for line in sf if line.strip()]
                
        if works_cited_urls:
            # Create list item links
            urls_html_items = "".join(f'<li><a href="{url}" class="text-blue-600 hover:underline" target="_blank">{url}</a></li>\n' for url in works_cited_urls)
            works_cited_html = f'<ol class="list-decimal list-inside space-y-2 mb-4 text-slate-600">\n{urls_html_items}</ol>'
            
            # Insert Works Cited section
            parsed["sections_html"]["Works Cited"] = works_cited_html
            if "Works Cited" not in parsed["sections_ordered"]:
                parsed["sections_ordered"].append("Works Cited")
                
        # Shuffle or select other topics for the Semiquincentennial Hub cards
        other_topics = [t for t in topics if t != topic_name]
        parsed["other_topics"] = other_topics
        parsed["other_topics_categories"] = topics_categories
        
        # Generate the final webpage
        page_html = insertDataIntoTemplate(template_html, parsed)
        
        # Write to destination
        dest_file = web_dir / f"{topic_name}.html"
        dest_file.write_text(page_html, encoding="utf-8")
        print(f"Saved {dest_file.name}")

if __name__ == "__main__":
    main()